apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  generation: 1
  labels:
    app: drainy
  name: drainy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drainy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drainy
    spec:
      serviceAccountName: drainy-sa
      containers:
      - image: yunshengyan/drainy:0.9
        imagePullPolicy: IfNotPresent
        name: leader
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
